#!/usr/bin/env bash
# Installs nginx web server.

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw enable
sudo ufw allow "Nginx HTTP"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
